command: ["uvicorn", "midas.backend.app:app", "--workers", "2"]

env:
  - name: OTEL_CATALOG
    value: "midas_catalog"
  - name: OTEL_SCHEMA
    value: "otel_raw"
  - name: OTEL_WAREHOUSE_ID
    value: "a6505a9626cf9ca7"
  - name: OTEL_SERVICE_NAME
    value: "midas"
